"""
The map backdrop behind the connection panel.

A stylised world map that highlights the country you are connected to and
**pans to centre it**, because a map fixed on Europe says nothing when you
connect to Japan. The move is animated, so it reads as the map travelling
there rather than teleporting.

Stylised, deliberately: flat fills in our own palette, no terrain, no labels.
It stays non-interactive - nothing here is clickable. (Clicking a country to
connect is worth doing later; it is not what makes the map useful.)

Outlines come from `map_data.py`, generated by `tools/make-map.py` from
public-domain Natural Earth data.
"""

import math
from typing import Optional, Tuple

from gi.repository import Gtk

from .map_data import COUNTRIES

#: Proton's country codes are not always ISO 3166-1 alpha-2. Their "UK" is
#: ISO "GB", and connecting to the United Kingdom simply highlighted nothing
#: until this existed.
COUNTRY_ALIASES = {
    "UK": "GB",
    "EL": "GR",   # occasionally used for Greece
}

#: Countries Proton offers that are too small to appear in 1:110m outline data
#: (Monaco, Singapore, Malta and friends). Rather than highlight nothing, the
#: map marks where they are, using the coordinates of the server itself.
MARKER_RADIUS = 9.0

#: Where the map sits when nothing is connected: Europe, roughly.
DEFAULT_VIEW = (10.0, 50.0, 90.0)     # centre longitude, centre latitude, span

#: How much longitude the view spans, clamped. Smaller = closer in.
#:
#: The floor is deliberately wide. The outlines are 1:110m - simplified for a
#: backdrop - so zooming close on a small country turns Belgium into a
#: pentagon. Staying regional keeps the shapes honest and gives the country
#: some context to sit in.
MIN_SPAN = 58.0
MAX_SPAN = 190.0

#: A country should fill about this much of the width when centred.
COUNTRY_FILL = 0.22

#: Seconds the pan takes.
ANIMATION_SECONDS = 0.85


def _shortest_longitude_delta(start: float, end: float) -> float:
    """Travel the short way round, not the long way across the Pacific."""
    delta = (end - start + 180.0) % 360.0 - 180.0
    return delta


def _ease_out(t: float) -> float:
    """Cubic ease-out: quick to start, settles gently."""
    return 1.0 - (1.0 - t) ** 3


def resolve_country(code: Optional[str]) -> Optional[str]:
    """Map a Proton country code to the one the outlines are keyed by."""
    if not code:
        return None
    code = code.upper()
    return COUNTRY_ALIASES.get(code, code)


def ring_area(ring) -> float:
    """Absolute shoelace area, in square degrees."""
    total = 0.0
    for index in range(len(ring)):
        x1, y1 = ring[index]
        x2, y2 = ring[(index + 1) % len(ring)]
        total += x1 * y2 - x2 * y1
    return abs(total) / 2


def country_extent(code: str) -> Optional[Tuple[float, float, float, float]]:
    """(centre_lon, centre_lat, width_deg, height_deg) for a country.

    Framed on the country's *largest* landmass, not on all of its territory.
    France owns French Guiana, so framing everything put the camera in the
    middle of the Atlantic with the mainland at one edge and South America at
    the other.
    """
    rings = COUNTRIES.get(resolve_country(code))
    if not rings:
        return None

    main = max(rings, key=ring_area)
    longitudes = [x for x, _ in main]
    latitudes = [y for _, y in main]
    if not longitudes:
        return None

    west, east = min(longitudes), max(longitudes)
    south, north = min(latitudes), max(latitudes)

    return ((west + east) / 2, (south + north) / 2, east - west, north - south)


class Backdrop(Gtk.DrawingArea):
    """A stylised world map that follows the connection."""

    # Deliberately understated: it is a backdrop, and it should not compete
    # with the connection panel in front of it. Brighter land was tried and
    # rejected.
    LAND_FILL = (1, 1, 1, 0.042)
    LAND_STROKE = (1, 1, 1, 0.085)

    HIGHLIGHT_FILL = (0.91, 0.72, 0.24, 0.30)
    HIGHLIGHT_STROKE = (0.96, 0.82, 0.42, 0.75)
    HIGHLIGHT_GLOW = (0.91, 0.72, 0.24, 0.10)

    def __init__(self):
        super().__init__()
        self.add_css_class("backdrop")
        self.set_hexpand(True)
        self.set_vexpand(True)
        # Decorative only: never take clicks or focus away from the panel.
        self.set_can_target(False)
        self.set_can_focus(False)

        self._highlight: Optional[str] = None
        self._marker: Optional[Tuple[float, float]] = None
        self._view = list(DEFAULT_VIEW)
        self._from_view = list(DEFAULT_VIEW)
        self._to_view = list(DEFAULT_VIEW)
        self._animation_start: Optional[float] = None
        self._tick_id: Optional[int] = None
        #: 0..1 - the highlight fades in as the map arrives, rather than
        #: appearing fully formed before the pan has finished.
        self._highlight_progress = 1.0

        self.set_draw_func(self._draw)

    # -- highlighting and framing -------------------------------------------

    @property
    def highlighted_country(self) -> Optional[str]:
        """ISO alpha-2 code currently picked out, if any."""
        return self._highlight

    @property
    def view(self) -> Tuple[float, float, float]:
        """Current (centre_lon, centre_lat, span)."""
        return tuple(self._view)

    def knows_country(self, country_code: str) -> bool:
        """Whether we have an outline for this country."""
        return resolve_country(country_code) in COUNTRIES

    def set_marker(self, longitude: Optional[float], latitude: Optional[float]) -> None:
        """Where to mark, for countries too small to have an outline."""
        self._marker = (longitude, latitude) if longitude and latitude else None
        self.queue_draw()

    def set_highlight(self, country_code: Optional[str], animate: bool = True) -> None:
        """Pick out a country and bring the map to it.

        Unknown codes clear the highlight and return to the default view: the
        map never claims to be somewhere it cannot show.
        """
        code = resolve_country(country_code)
        if code == self._highlight:
            return

        self._highlight = resolve_country(code)
        target = self._view_for(self._highlight)
        if animate:
            self._highlight_progress = 0.0
            self._animate_to(target)
        else:
            self._highlight_progress = 1.0
            self._view = list(target)
            self.queue_draw()

    def _view_for(self, code: Optional[str]):
        """The view that frames `code`, or the default view."""
        extent = country_extent(code) if code else None
        if extent is None:
            if self._marker is not None:
                longitude, latitude = self._marker
                return [longitude, latitude, MIN_SPAN * 1.6]
            return list(DEFAULT_VIEW)

        centre_lon, centre_lat, width_deg, height_deg = extent
        # Frame by whichever dimension is larger, so tall countries fit too.
        span = max(width_deg, height_deg * 1.6) / COUNTRY_FILL
        span = max(MIN_SPAN, min(span, MAX_SPAN))
        return [centre_lon, centre_lat, span]

    # -- animation ----------------------------------------------------------

    def _animate_to(self, target) -> None:
        self._from_view = list(self._view)
        self._to_view = list(target)
        self._animation_start = None

        if self._tick_id is None:
            self._tick_id = self.add_tick_callback(self._on_tick)

    def _on_tick(self, _widget, frame_clock) -> bool:
        now = frame_clock.get_frame_time() / 1_000_000.0
        if self._animation_start is None:
            self._animation_start = now

        elapsed = now - self._animation_start
        progress = min(elapsed / ANIMATION_SECONDS, 1.0)
        eased = _ease_out(progress)

        start_lon, start_lat, start_span = self._from_view
        _, end_lat, end_span = self._to_view
        delta_lon = _shortest_longitude_delta(start_lon, self._to_view[0])

        self._view = [
            start_lon + delta_lon * eased,
            start_lat + (end_lat - start_lat) * eased,
            start_span + (end_span - start_span) * eased,
        ]
        # Fade the highlight in over the back half of the journey.
        self._highlight_progress = max(0.0, min((eased - 0.35) / 0.65, 1.0))
        self.queue_draw()

        if progress >= 1.0:
            self._highlight_progress = 1.0
            self._tick_id = None
            self._animation_start = None
            return False
        return True

    # -- projection ---------------------------------------------------------

    def ring_points(self, ring, width, height):
        """Project one ring, keeping it continuous.

        Longitudes are unwrapped *along the ring* rather than each point being
        placed independently. Taking the shortest route from the view centre
        for every point separately tears any country that crosses the
        antimeridian - Russia, Fiji, Alaska - because two neighbouring points
        land at opposite edges and get joined by a line straight across the
        map. Accumulating the shortest step between consecutive points keeps
        the outline whole; the parts off-screen are simply clipped.
        """
        centre_lon, centre_lat, span = self._view
        cos_lat = max(math.cos(math.radians(centre_lat)), 0.2)
        scale = width / (span * cos_lat)

        points = []
        offset = None
        previous_lon = None
        for longitude, latitude in ring:
            if offset is None:
                offset = _shortest_longitude_delta(centre_lon, longitude)
            else:
                offset += _shortest_longitude_delta(previous_lon, longitude)
            previous_lon = longitude

            x = width / 2 + offset * cos_lat * scale
            y = height / 2 - (latitude - centre_lat) * scale
            points.append((x, y))
        return points

    # -- drawing -----------------------------------------------------------

    def _draw(self, _area, context, width, height):
        if width <= 0 or height <= 0:
            return

        self._draw_wash(context, width, height)

        context.set_line_width(1.0)
        for code, rings in COUNTRIES.items():
            if code == self._highlight:
                continue   # drawn last, on top
            for ring in rings:
                if not self._trace(context, ring, width, height):
                    continue
                context.set_source_rgba(*self.LAND_FILL)
                context.fill_preserve()
                context.set_source_rgba(*self.LAND_STROKE)
                context.stroke()

        if self._highlight in COUNTRIES:
            self._draw_highlight(context, width, height)

        # The pin sits on top of the highlight, not instead of it. They appear
        # and disappear together; a lone dot means the country outline is too
        # small to draw, not that something went wrong mid-switch.
        if self._marker is not None:
            self._draw_marker(context, width, height,
                              alone=self._highlight not in COUNTRIES)

    def _draw_wash(self, context, width, height):
        """A soft pool of violet light, brightest behind the panel."""
        import cairo

        radius = max(width, height) * 0.72
        gradient = cairo.RadialGradient(
            width / 2, height * 0.44, 0,
            width / 2, height * 0.44, radius,
        )
        gradient.add_color_stop_rgba(0.0, 0.44, 0.36, 0.76, 0.11)
        gradient.add_color_stop_rgba(0.55, 0.32, 0.26, 0.58, 0.05)
        gradient.add_color_stop_rgba(1.0, 0.10, 0.09, 0.16, 0.0)

        context.set_source(gradient)
        context.rectangle(0, 0, width, height)
        context.fill()

    def _draw_marker(self, context, width, height, alone: bool = False):
        """Pin the server's own location.

        Drawn small over a highlighted country, and larger when it is carrying
        the whole job on its own - which happens for Monaco, Singapore, Malta
        and the others too small to exist in 1:110m outlines.
        """
        longitude, latitude = self._marker
        points = self.ring_points([(longitude, latitude)], width, height)
        if not points:
            return

        x, y = points[0]
        fade = self._highlight_progress
        radius = MARKER_RADIUS if alone else MARKER_RADIUS * 0.42

        context.set_source_rgba(*self.HIGHLIGHT_GLOW[:3],
                                self.HIGHLIGHT_GLOW[3] * fade)
        context.arc(x, y, radius * 2.2, 0, 2 * math.pi)
        context.fill()

        # Solid, and brighter than the country fill it sits on: a translucent
        # dot over a gold country is invisible.
        context.set_source_rgba(1.0, 0.90, 0.55, 0.95 * fade)
        context.arc(x, y, radius, 0, 2 * math.pi)
        context.fill()

        # A dark rim separates it from the fill underneath.
        context.set_source_rgba(0.10, 0.09, 0.14, 0.75 * fade)
        context.arc(x, y, radius, 0, 2 * math.pi)
        context.set_line_width(1.4)
        context.stroke()

    def _draw_highlight(self, context, width, height):
        rings = COUNTRIES[self._highlight]
        fade = self._highlight_progress
        if fade <= 0.0:
            return

        def faded(colour):
            return colour[0], colour[1], colour[2], colour[3] * fade

        context.set_line_width(7.0)
        context.set_source_rgba(*faded(self.HIGHLIGHT_GLOW))
        for ring in rings:
            if self._trace(context, ring, width, height):
                context.stroke()

        for ring in rings:
            if not self._trace(context, ring, width, height):
                continue
            context.set_source_rgba(*faded(self.HIGHLIGHT_FILL))
            context.fill_preserve()
            context.set_source_rgba(*faded(self.HIGHLIGHT_STROKE))
            context.set_line_width(1.4)
            context.stroke()

    def _trace(self, context, ring, width, height) -> bool:
        """Build the path for one ring. False if it is entirely off-screen."""
        points = self.ring_points(ring, width, height)
        if len(points) < 2:
            return False

        margin = max(width, height)
        if all(x < -margin for x, _ in points) or all(x > width + margin for x, _ in points):
            return False
        if all(y < -margin for _, y in points) or all(y > height + margin for _, y in points):
            return False

        context.move_to(*points[0])
        for point in points[1:]:
            context.line_to(*point)
        context.close_path()
        return True
